// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVZcNgHGL-tNLoKtP6p0oVx3eKl0bhGXA',
    appId: '1:195258799714:web:d181f29d4cae0fc5a7e33b',
    messagingSenderId: '195258799714',
    projectId: 'selfie-51ca6',
    authDomain: 'selfie-51ca6.firebaseapp.com',
    storageBucket: 'selfie-51ca6.appspot.com',
    measurementId: 'G-7XVC955DYF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSSVUwIuBF649nGW1d6Ggs6bKZXPS-4wQ',
    appId: '1:195258799714:android:35a11cd8f2ab45d8a7e33b',
    messagingSenderId: '195258799714',
    projectId: 'selfie-51ca6',
    storageBucket: 'selfie-51ca6.appspot.com',

  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzoTTTHBerX8t7tFCGnfgSJeB1CrRSZ4s',
    appId: '1:195258799714:ios:6826c5906284ea8ba7e33b',
    messagingSenderId: '195258799714',
    projectId: 'selfie-51ca6',
    storageBucket: 'selfie-51ca6.appspot.com',
    iosClientId: '195258799714-vpks8f7md1io7olg445p51jrc4modfec.apps.googleusercontent.com',
    iosBundleId: 'com.example.selfie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzoTTTHBerX8t7tFCGnfgSJeB1CrRSZ4s',
    appId: '1:195258799714:ios:615ce0211d8c6ed8a7e33b',
    messagingSenderId: '195258799714',
    projectId: 'selfie-51ca6',
    storageBucket: 'selfie-51ca6.appspot.com',
    iosClientId: '195258799714-8rjkj0cbht926fggf2etodviofdalplo.apps.googleusercontent.com',
    iosBundleId: 'com.example.selfie.RunnerTests',
  );
}
